/*
 * LAS 5 MISIONES
 * --------------
 * Cada escena apunta a una pregunta del banco maestro (q: 'Q..').
 * "opciones" traduce los códigos maestros al lenguaje de la historia.
 * Si una opción no se traduce, se usa el texto del banco maestro.
 *
 * medidor: la barra de progreso temática de cada historia.
 *   de / a   -> valor inicial y final (puede bajar, como el oxígeno)
 */
const HISTORIAS = {

  /* ───────────────────────────── SHERLOCK ───────────────────────────── */
  sherlock: {
    titulo: 'El caso de la habitación 23',
    etiqueta: 'SHERLOCK',
    icono: '🕵️',
    color: '#d4a64a',
    resumen: 'Un misterio. Pistas. Sospechosos. Mentiras. Tendrás que descubrir quién está ocultando la verdad.',
    medidor: { nombre: 'Pistas', de: 0, a: 17, formato: v => `${v}/17` },
    intro: [
      'Londres, 1895. 11:47 p. m. La niebla se pega a las ventanas del 221B de Baker Street.',
      'Sherlock Holmes lleva tres días desaparecido. Antes de irse te dejó una nota: <em>"Si alguien toca la puerta, el caso es tuyo."</em>',
      'Alguien toca la puerta.',
      'Una mujer empapada te entrega un sobre. Dentro hay una llave con el número 23 y una frase escrita a mano: <strong>"NO CONFÍES EN NADIE."</strong>',
      'Eres el nuevo detective. Y el caso acaba de empezar.',
    ],
    escenas: [
      {
        q: 'Q00',
        texto: ['Antes de salir, Holmes siempre revisaba su "estado de detective". Decía que una mente cansada no ve las pistas.',
          'Te miras en el espejo del pasillo. Honestamente...'],
        pregunta: '¿Cómo está tu energía estas últimas semanas?',
        opciones: {
          llena: '🔋 Llena: estoy listo(a) para cualquier caso',
          media: '🔋 A la mitad: puedo, pero ando cansado(a)',
          baja: '🪫 Baja: me está costando más de lo normal',
          critica: '🪫 Casi vacía: estoy agotado(a) por dentro',
          apagada: '⚫ Apagada: siento que ya no puedo más',
        },
      },
      {
        q: 'Q02',
        texto: ['Llegas al Hotel Langham. En el salón principal hay una fiesta: música, risas, copas que chocan. Todos parecen conocerse.',
          'Tu investigación necesita que hables con alguien... pero nadie te conoce.'],
        pregunta: 'Entras al salón. ¿Qué haces?',
        opciones: {
          integra: 'Me acerco a un grupo y empiezo a conversar',
          espera: 'Me quedo cerca, esperando a que alguien me hable',
          margen: 'Me quedo en una esquina observando todo desde lejos',
          ausente: 'Estoy ahí, pero honestamente quisiera estar en otro lugar',
        },
      },
      {
        q: 'Q01',
        texto: ['De pronto, un grito. Las luces se apagan. Cuando vuelven, el mayordomo está en el suelo, desmayado, junto a la escalera que lleva a la habitación 23.',
          'La gente empieza a empujar hacia la salida. Alguien grita: "¡Que alguien haga algo!"'],
        pregunta: '¿Qué haces?',
        opciones: {
          control: 'Me pongo al frente y empiezo a dar instrucciones',
          ayuda: 'Busco a alguien con experiencia que sepa qué hacer',
          calma: 'Intento tranquilizar a la gente que está en pánico',
          bloqueo: 'Me quedo congelado(a); no sé qué hacer',
          huir: 'Quiero salir de ahí lo antes posible',
        },
      },
      {
        q: 'Q03',
        texto: ['Es la 1:12 a. m. Rentas un cuarto en el hotel para seguir mañana. Te acuestas, pero tu mente no se apaga.',
          'Holmes decía: "Lo que ocupa tu cabeza de noche es la pista más honesta que tienes sobre ti mismo."'],
        pregunta: 'Además del caso, ¿qué ocupa más espacio en tu cabeza últimamente? (elige hasta 3)',
      },
      {
        q: 'Q04',
        texto: ['No logras dormir. Sientes un peso en el pecho, esa sensación de cuando las cosas no están bien.',
          'Cada detective tiene su manera de lidiar con los días malos. Holmes tocaba el violín a las 3 a. m.'],
        pregunta: 'En tu vida real, ¿qué haces normalmente cuando estás mal? (elige hasta 3)',
      },
      {
        q: 'Q05',
        texto: ['A la mañana siguiente encuentras la primera gran pista: una carta firmada por el inspector Lestrade, tu mayor aliado en Scotland Yard.',
          'Él sabía todo desde el principio. Te estuvo mintiendo.'],
        pregunta: 'La persona en la que más confiabas te mintió. ¿Qué haces?',
        opciones: {
          confronta: 'Voy directo a confrontarlo y a pedirle una explicación',
          aleja: 'Me alejo sin decir nada; ya no cuento con él',
          perdona: 'Me duele, pero intento entender y perdonar',
          desconfia: 'Desde ahora no confío en nadie más',
          culpa: 'Pienso que fue mi culpa por ser tan ingenuo(a)',
          finge: 'Hago como que no pasó nada y sigo',
        },
      },
      {
        q: 'Q06',
        texto: ['Sigues la pista hasta los túneles bajo el Támesis. Tu vela se apaga. Oscuridad total. Escuchas pasos que se acercan.',
          'Recuerdas a la señora Hudson despidiéndote: "Dios va contigo, no tienes nada que temer."',
          'Pero ahora mismo tu corazón late a mil.'],
        pregunta: '¿Qué pensamiento se parecería más al tuyo en ese momento?',
      },
      {
        q: 'Q07',
        texto: ['Sales de los túneles. Es domingo y las campanas de la abadía están sonando. Entras a la iglesia a recuperar el aliento.',
          'Te sientas en la última banca. Nadie te ve. Nadie te está evaluando.'],
        pregunta: 'Si eres completamente honesto(a), ¿cómo describirías tu relación con Dios hoy?',
      },
      {
        q: 'Q08',
        texto: ['En la banca alguien dejó una libreta abierta con una sola frase: <em>"Si pudieras preguntarle algo a Dios sin miedo a que nadie te juzgue..."</em>',
          'Debajo hay espacio en blanco. La pluma está ahí. Nadie sabrá que fuiste tú.'],
        pregunta: '¿Qué le preguntarías a Dios?',
        placeholder: 'Escribe tu pregunta...',
      },
      {
        q: 'Q09',
        texto: ['Encuentras a la mujer del sobre. Está temblando. Te confiesa que sabe algo, pero que le da terror decirlo en voz alta.',
          'La entiendes. Hay frases que pesan más que otras.'],
        pregunta: '¿Qué frases te costaría más decirle a alguien cuando estás pasando por algo? (elige hasta 3)',
      },
      {
        q: 'Q10',
        texto: ['Llegas a un baile de máscaras donde se esconde el sospechoso principal. En la entrada te ofrecen una máscara para no ser reconocido(a).',
          'Cada máscara tiene una frase grabada. Curiosamente, se parecen a las que usamos en la vida real.'],
        pregunta: '¿Cuál se parece más a la que tú usas cuando estás con otras personas?',
        opciones: { ninguna: 'Ninguna: entro sin máscara, soy igual en todos lados' },
      },
      {
        q: 'Q11',
        texto: ['En la habitación 23 por fin encuentras la caja fuerte. No tiene números: tiene una ranura para papel y una inscripción:',
          '<strong>"Solo se abre con una verdad que casi nunca dices."</strong>'],
        pregunta: 'Completa la frase para abrir la caja: "Hay algo que últimamente me preocupa y casi nunca digo..."',
        placeholder: 'Hay algo que me preocupa y casi nunca digo...',
        boton: 'ABRIR CAJA 🔓',
      },
      {
        q: 'Q12',
        texto: ['La caja se abre... y está vacía. Alguien llegó antes. Te equivocaste de sospechoso y perdiste dos días.',
          'Scotland Yard se burla de ti. Parece que fracasaste.'],
        pregunta: 'Cuando fracasas en algo importante, ¿qué pasa normalmente dentro de ti?',
        opciones: {
          levanta: 'Me levanto y lo intento de nuevo',
          insuficiente: 'Pienso que no soy suficiente',
          compara: 'Me comparo: "Holmes sí lo habría logrado"',
          culpa: 'Me culpo durante mucho tiempo',
          aprobacion: 'Necesito que alguien me diga que está bien',
          meda: 'Me desconecto; me da igual',
        },
      },
      {
        q: 'Q13',
        nivelSecreto: true,
        texto: ['Has llegado demasiado lejos para seguir respondiendo en automático.',
          'Esta pregunta no tiene puntos. Nadie sabrá que la escribiste tú.'],
        pregunta: '¿Hay alguna lucha personal de la que te gustaría poder hablar con alguien de confianza?',
        seguimiento: 'Si quieres, escríbela aquí. No pongas tu nombre.',
      },
      {
        q: 'Q14',
        texto: ['Todo conduce a la bodega del muelle 7. Ahí te esperan los "villanos" del caso... pero no son personas: son las cosas que han estado detrás de todo.',
          'No puedes enfrentarlas todas al mismo tiempo.'],
        pregunta: 'EL JEFE FINAL: si pudieras enfrentar solo una en tu vida real, ¿cuál sería primero?',
      },
      {
        q: 'Q15',
        texto: ['Justo antes de entrar, Watson aparece. "Holmes nunca resolvió un caso solo", te dice. "¿Qué necesitas de nosotros?"'],
        pregunta: 'Pensando en tu vida real: ¿qué necesitarías de la iglesia para ayudarte con eso? (elige hasta 3)',
      },
      {
        q: 'Q16',
        texto: ['Resuelves el caso. La mujer del sobre no escondía un crimen: escondía algo que la avergonzaba y creía que nadie la iba a entender.',
          'Cuando por fin lo dijo, el misterio se deshizo.',
          'Holmes aparece en la puerta, sonriendo: "El caso más difícil nunca es el de los demás. Es el nuestro."'],
        pregunta: 'Si pudieras pedirle una sola cosa a Dios para esta etapa de tu vida, ¿qué sería?',
        placeholder: 'Le pediría...',
      },
    ],
    cierre: 'CASO RESUELTO',
  },

  /* ───────────────────────────── SUBMARINO ───────────────────────────── */
  submarino: {
    titulo: '7 minutos para escapar',
    etiqueta: 'SUBMARINO',
    icono: '🌊',
    color: '#2ec4d6',
    resumen: 'Una falla crítica. Oxígeno limitado. Tu equipo empieza a entrar en pánico. Decisiones bajo presión.',
    medidor: { nombre: 'Oxígeno', de: 100, a: 6, formato: v => `${v}%` },
    intro: [
      'Submarino de investigación <strong>ABISMO-7</strong>. Profundidad: 3,214 metros.',
      'Llevas dos semanas con la tripulación estudiando una fosa del Pacífico. Todo iba bien... hasta hace 30 segundos.',
      'Un golpe sacude el casco. Las luces se vuelven rojas. Una voz robótica anuncia:',
      '<strong>"FALLA CRÍTICA. SISTEMA DE OXÍGENO COMPROMETIDO."</strong>',
      'La cápsula de escape está al otro lado de la nave. Tienes que llegar.',
    ],
    escenas: [
      {
        q: 'Q00',
        texto: ['La computadora pide calibrar tu traje. Un escáner recorre tu cuerpo y aparece una pregunta en la pantalla:',
          '<em>"Estado del tripulante: ¿cómo ha estado su nivel de energía en las últimas semanas?"</em>'],
        pregunta: 'Sé honesto(a). ¿Cómo está tu batería estas semanas?',
        opciones: {
          llena: '🔋 Llena: me siento bien',
          media: '🔋 A la mitad: bien, pero cansado(a)',
          baja: '🪫 Baja: me está costando',
          critica: '🪫 Casi vacía: estoy agotado(a) por dentro',
          apagada: '⚫ Apagada: siento que ya no puedo más',
        },
      },
      {
        q: 'Q02',
        texto: ['Llegas al comedor, el punto de reunión de emergencia. La tripulación está ahí, hablando entre ellos, formando grupos para decidir qué hacer.',
          'Eres el/la más nuevo(a) a bordo.'],
        pregunta: '¿Qué haces?',
        opciones: {
          integra: 'Me meto a la conversación y doy mi opinión',
          espera: 'Espero a que alguien me incluya',
          margen: 'Me quedo aparte revisando mi tablet',
          ausente: 'Estoy ahí, pero quisiera estar en cualquier otro lugar',
        },
      },
      {
        q: 'Q01',
        texto: ['Una segunda alarma. El agua empieza a filtrarse por el piso. Nadie sabe exactamente qué está pasando.',
          'La ingeniera grita: <strong>"¡Tenemos que hacer algo YA!"</strong>'],
        pregunta: '¿Qué haces?',
        opciones: {
          control: 'Tomo el control y empiezo a dar órdenes',
          ayuda: 'Busco al capitán o a quien sepa qué hacer',
          calma: 'Intento tranquilizar a todos',
          bloqueo: 'Me bloqueo y no puedo moverme',
          huir: 'Corro a esconderme donde no me alcance el agua',
        },
      },
      {
        q: 'Q03',
        texto: ['Tienen que esperar 10 minutos a que la presión se estabilice para abrir la siguiente compuerta.',
          'Silencio. Solo se escucha el goteo. Y en silencio la mente empieza a hablar.'],
        pregunta: 'Si no estuvieras en este submarino, ¿qué ocuparía tu cabeza últimamente? (elige hasta 3)',
      },
      {
        q: 'Q04',
        texto: ['El médico de a bordo reparte mascarillas y dice: "Cada quien reacciona diferente cuando las cosas se ponen feas. No hay forma correcta."'],
        pregunta: 'En tu vida real, ¿qué haces normalmente cuando estás mal? (elige hasta 3)',
      },
      {
        q: 'Q05',
        texto: ['Descubres algo terrible: Marcos, tu compañero de camarote, sabía de la falla desde hace días. No dijo nada porque le daba miedo que lo culparan.',
          'Él era tu amigo a bordo.'],
        pregunta: 'Alguien en quien confiabas te falló. ¿Qué haces?',
        opciones: {
          confronta: 'Lo encaro y le digo lo que siento',
          aleja: 'Me alejo de él sin decir nada',
          perdona: 'Me duele, pero lo perdono; todos tenemos miedo',
          desconfia: 'Desde ahora no confío en nadie de la tripulación',
          culpa: 'Pienso que yo debí darme cuenta; es mi culpa',
          finge: 'Hago como si nada y sigo',
        },
      },
      {
        q: 'Q06',
        texto: ['<strong>Oxígeno bajando.</strong> La compuerta está atascada.',
          'Tu compañero cierra los ojos y dice: "Dios nos va a ayudar. No tenemos nada que temer."',
          'Pero tú estás aterrado(a).'],
        pregunta: '¿Qué pensamiento se parecería más al tuyo?',
      },
      {
        q: 'Q07',
        texto: ['Logran abrir la compuerta. Mientras todos recuperan el aire, te quedas mirando por la escotilla: oscuridad total, 3,000 metros de agua encima.',
          'Te sientes muy pequeño(a). Y piensas en Dios.'],
        pregunta: 'Si eres completamente honesto(a), ¿cómo describirías tu relación con Dios hoy?',
      },
      {
        q: 'Q08',
        texto: ['En la pared de la cápsula de comunicaciones hay una grabadora. Los tripulantes la usan para dejar mensajes por si no regresan.',
          'Presionas el botón. Nadie más lo va a escuchar.'],
        pregunta: 'Si pudieras hacerle una pregunta a Dios sin miedo a que nadie te juzgue, ¿qué le preguntarías?',
        placeholder: 'Escribe tu pregunta...',
      },
      {
        q: 'Q09',
        texto: ['Por la radio entra la voz de la base en la superficie: "ABISMO-7, ¿cuál es su estado? Necesitamos saber la verdad para poder ayudarlos."',
          'Todos se miran. Nadie quiere admitir lo mal que están.'],
        pregunta: 'En tu vida, ¿qué te costaría más decirle a alguien cuando estás pasando por algo? (elige hasta 3)',
      },
      {
        q: 'Q10',
        texto: ['En el casillero de equipo hay cascos con visores reflejantes. Desde afuera nadie ve tu cara, solo una frase proyectada en el visor.',
          'Todos en la tripulación usan uno. Cada quien escoge qué mostrar.'],
        pregunta: '¿Qué frase mostraría tu visor cuando estás con otras personas?',
        opciones: { ninguna: 'Ninguna: me quito el casco, soy igual en todos lados' },
      },
      {
        q: 'Q11',
        texto: ['La cápsula de escape tiene un último seguro. En la pantalla aparece:',
          '<strong>"CÓDIGO DE LIBERACIÓN: ESCRIBA UNA VERDAD QUE CASI NUNCA DICE."</strong>',
          'El ingeniero que la diseñó era raro. Pero no hay otra forma.'],
        pregunta: 'Completa: "Hay algo que últimamente me preocupa y casi nunca digo..."',
        placeholder: 'Hay algo que me preocupa y casi nunca digo...',
        boton: 'LIBERAR SEGURO 🔓',
      },
      {
        q: 'Q12',
        texto: ['Presionas el botón de lanzamiento... y falla. Te equivocaste de secuencia y el sistema se reinicia. Perdieron un minuto de oxígeno por tu error.',
          'Todos te miran.'],
        pregunta: 'Cuando fallas en algo importante, ¿qué pasa normalmente dentro de ti?',
        opciones: {
          levanta: 'Respiro y lo intento de nuevo',
          insuficiente: 'Pienso que no soy suficiente para esto',
          compara: 'Pienso: "cualquier otro lo habría hecho mejor"',
          culpa: 'Me culpo, aunque ya haya pasado',
          aprobacion: 'Necesito que alguien me diga que está bien',
          meda: 'Me desconecto; me da igual',
        },
      },
      {
        q: 'Q13',
        nivelSecreto: true,
        texto: ['Hay un compartimento que no aparece en los planos. Adentro solo hay una pantalla.',
          'Esta pregunta no tiene puntos. Nadie sabrá que la respondiste tú.'],
        pregunta: '¿Hay alguna lucha personal de la que te gustaría poder hablar con alguien de confianza?',
        seguimiento: 'Si quieres, escríbela aquí. No pongas tu nombre.',
      },
      {
        q: 'Q14',
        texto: ['<strong>ÚLTIMA DECISIÓN.</strong> Solo hay energía para sellar una compuerta más. Cada una tiene escrito el nombre de lo que está inundando tu vida.',
          'No puedes sellarlas todas. Solo una.'],
        pregunta: 'EL JEFE FINAL: en tu vida real, ¿cuál enfrentarías primero?',
      },
      {
        q: 'Q15',
        texto: ['La cápsula de escape tiene una regla de diseño: <strong>no se puede lanzar con una sola persona</strong>. Necesita dos llaves, giradas al mismo tiempo.',
          'Nadie sale de aquí solo.'],
        pregunta: 'En tu vida real, ¿qué necesitarías de la iglesia para no cargar esto solo(a)? (elige hasta 3)',
      },
      {
        q: 'Q16',
        texto: ['Giran las llaves. La cápsula se dispara hacia arriba. 3,000... 2,000... 500 metros...',
          'Salen a la superficie justo cuando está amaneciendo. El aire nunca se había sentido tan bien.',
          'Te das cuenta de algo: no te salvó ser el/la más fuerte. Te salvó no estar solo(a).'],
        pregunta: 'Mirando el amanecer: si pudieras pedirle una sola cosa a Dios para esta etapa de tu vida, ¿qué sería?',
        placeholder: 'Le pediría...',
      },
    ],
    cierre: 'HAS ESCAPADO',
  },

  /* ───────────────────────────── ASESINO ───────────────────────────── */
  asesino: {
    titulo: 'La última noche',
    etiqueta: 'EL CULPABLE',
    icono: '🔪',
    color: '#e05252',
    resumen: 'Un grupo de amigos. Una casa aislada. Alguien está mintiendo. Descubre quién antes del amanecer.',
    medidor: { nombre: 'Hora', de: 22, a: 38, formato: v => { const h = Math.floor(v) % 24; return `${String(h).padStart(2, '0')}:00`; } },
    intro: [
      'Una cabaña en la montaña. Tormenta afuera. Sin señal. Ocho amigos celebrando el cumpleaños de Dani.',
      'A las 10:00 p. m. se va la luz.',
      'Cuando vuelve, Dani está en el suelo del sótano, inconsciente. Respira, pero no despierta. Y en la pared alguien escribió:',
      '<strong>"UNO DE USTEDES SABE LO QUE PASÓ."</strong>',
      'El camino está bloqueado hasta el amanecer. Tienes hasta las 6:00 a. m. para descubrir quién fue.',
    ],
    escenas: [
      {
        q: 'Q00',
        texto: ['Antes de empezar a investigar te sientas un momento en la escalera. Tienes que estar lúcido(a) toda la noche.',
          'Pero la verdad es que ya venías cargando cosas desde antes de llegar aquí.'],
        pregunta: '¿Cómo está tu batería estas últimas semanas?',
        opciones: {
          llena: '🔋 Llena: me siento bien',
          media: '🔋 A la mitad: bien, pero cansado(a)',
          baja: '🪫 Baja: me está costando',
          critica: '🪫 Casi vacía: estoy agotado(a) por dentro',
          apagada: '⚫ Apagada: siento que ya no puedo más',
        },
      },
      {
        q: 'Q02',
        texto: ['Todos se reúnen en la sala alrededor de la chimenea. Algunos se conocen desde niños. Tú conociste a la mayoría hace poco.',
          'Hablan todos al mismo tiempo.'],
        pregunta: '¿Qué haces?',
        opciones: {
          integra: 'Me meto a la conversación y participo',
          espera: 'Espero a que alguien me pregunte algo',
          margen: 'Me quedo en el sillón del rincón, observando',
          ausente: 'Estoy ahí, pero quisiera estar en mi casa',
        },
      },
      {
        q: 'Q01',
        texto: ['Un golpe en el piso de arriba. Alguien grita. Sofía llora, Andrés quiere salir a la tormenta, y Leo empieza a acusar a todos.',
          'El caos se está saliendo de control.'],
        pregunta: '¿Qué haces?',
        opciones: {
          control: 'Tomo el control: "¡Todos a la sala, ahora!"',
          ayuda: 'Busco a quien parezca saber qué hacer',
          calma: 'Intento calmar a Sofía y a los demás',
          bloqueo: 'Me quedo paralizado(a)',
          huir: 'Me encierro en un cuarto hasta que pase',
        },
      },
      {
        q: 'Q03',
        texto: ['Medianoche. Hacen turnos de guardia. Te toca descansar, pero no puedes dormir.',
          'Curiosamente, no es solo el misterio lo que no te deja en paz. Son otras cosas. Las de siempre.'],
        pregunta: 'Además del caso, ¿qué ocupa más espacio en tu cabeza últimamente? (elige hasta 3)',
      },
      {
        q: 'Q04',
        texto: ['Sientes un nudo en la garganta. Esa sensación de cuando todo se junta.'],
        pregunta: 'En tu vida real, ¿qué haces normalmente cuando estás mal? (elige hasta 3)',
      },
      {
        q: 'Q05',
        texto: ['Revisas los celulares. En el de Camila, tu mejor amiga del grupo, encuentras mensajes donde se burla de ti con los demás.',
          'Ella fue quien te invitó a esta fiesta.'],
        pregunta: 'La persona en quien más confiabas te falló. ¿Qué haces?',
        opciones: {
          confronta: 'La confronto ahí mismo',
          aleja: 'Me alejo de ella sin decir nada',
          perdona: 'Me duele, pero intento perdonar',
          desconfia: 'Decido no volver a confiar en nadie de aquí',
          culpa: 'Pienso que algo hice mal para merecerlo',
          finge: 'Hago como si no hubiera visto nada',
        },
      },
      {
        q: 'Q06',
        texto: ['3:00 a. m. Se apagan de nuevo las luces. Escuchas pasos en el pasillo que se acercan a tu puerta.',
          'Tomás, a tu lado, susurra: "Tranquilo(a). Dios está aquí. No tenemos nada que temer."',
          'Pero tú estás temblando.'],
        pregunta: '¿Qué pensamiento se parecería más al tuyo?',
      },
      {
        q: 'Q07',
        texto: ['Los pasos se alejan. Nadie entra. Tomás ya se durmió.',
          'Tú te quedas despierto(a) mirando el techo, en la oscuridad. Nadie te ve.'],
        pregunta: 'Si eres completamente honesto(a), ¿cómo describirías tu relación con Dios hoy?',
      },
      {
        q: 'Q08',
        texto: ['En la mesita de noche hay una Biblia vieja de la abuela de Dani. Entre sus páginas hay notas de otras personas, preguntas escritas a lápiz.',
          'Hay una hoja en blanco al final.'],
        pregunta: 'Si pudieras hacerle una pregunta a Dios sin miedo a que nadie te juzgue, ¿qué le preguntarías?',
        placeholder: 'Escribe tu pregunta...',
      },
      {
        q: 'Q09',
        texto: ['4:00 a. m. Proponen un juego para descubrir al culpable: cada quien tiene que decir una frase que le cueste decir en voz alta.',
          'El problema es que hay frases que pesan más que un secreto.'],
        pregunta: '¿Qué frases te costaría más decirle a alguien cuando estás pasando por algo? (elige hasta 3)',
      },
      {
        q: 'Q10',
        texto: ['En el ático encuentran una caja de disfraces con máscaras. Alguien las reparte en broma: "Así nadie sabe quién es quién."',
          'Pero cada máscara tiene una frase escrita adentro, y todas suenan demasiado familiares.'],
        pregunta: '¿Cuál se parece más a la que tú usas cuando estás con otras personas?',
        opciones: { ninguna: 'Ninguna: no me pongo máscara, soy igual en todos lados' },
      },
      {
        q: 'Q11',
        texto: ['Encuentras el diario de Dani. Tiene un candado de letras. En la tapa está escrito:',
          '<strong>"Para leer mi verdad, primero escribe la tuya."</strong>'],
        pregunta: 'Completa para abrirlo: "Hay algo que últimamente me preocupa y casi nunca digo..."',
        placeholder: 'Hay algo que me preocupa y casi nunca digo...',
        boton: 'ABRIR DIARIO 🔓',
      },
      {
        q: 'Q12',
        texto: ['Acusas a Leo frente a todos. Él llora y demuestra que estaba en la cocina. Te equivocaste. Ahora todos desconfían de ti.'],
        pregunta: 'Cuando fallas frente a otros, ¿qué pasa normalmente dentro de ti?',
        opciones: {
          levanta: 'Pido perdón y sigo intentando',
          insuficiente: 'Pienso que no soy suficiente',
          compara: 'Me comparo con los que sí lo hacen bien',
          culpa: 'Me culpo durante mucho tiempo',
          aprobacion: 'Necesito que alguien me diga que está bien',
          meda: 'Me desconecto; me da igual',
        },
      },
      {
        q: 'Q13',
        nivelSecreto: true,
        texto: ['Detrás del espejo del baño hay una puerta que nadie había visto.',
          'Esta habitación no aparece en ningún plano. Esta pregunta no tiene puntos. Nadie sabrá que fuiste tú.'],
        pregunta: '¿Hay alguna lucha personal de la que te gustaría poder hablar con alguien de confianza?',
        seguimiento: 'Si quieres, escríbela aquí. No pongas tu nombre.',
      },
      {
        q: 'Q14',
        texto: ['5:30 a. m. Por fin lo entiendes: en esta casa nadie es un monstruo. Pero todos cargan algo que los está consumiendo en la oscuridad.',
          'Solo te queda tiempo para enfrentar una cosa.'],
        pregunta: 'EL JEFE FINAL: en tu vida real, ¿cuál enfrentarías primero?',
      },
      {
        q: 'Q15',
        texto: ['Dani despierta. Te mira y dice: "Me caí sola. Bajé al sótano a llorar para que nadie me viera... y me resbalé. Escribí eso en la pared hace semanas, esperando que alguien lo notara."'],
        pregunta: 'Pensando en tu vida real, ¿qué necesitarías de la iglesia para no tener que esconderte? (elige hasta 3)',
      },
      {
        q: 'Q16',
        texto: ['6:00 a. m. Sale el sol. La tormenta pasó.',
          'No había asesino. Había una persona que llevaba mucho tiempo sufriendo en silencio, rodeada de amigos que nunca preguntaron.',
          'Lo que se esconde en la oscuridad crece. Lo que sale a la luz empieza a sanar.'],
        pregunta: 'Si pudieras pedirle una sola cosa a Dios para esta etapa de tu vida, ¿qué sería?',
        placeholder: 'Le pediría...',
      },
    ],
    cierre: 'EL MISTERIO SE RESOLVIÓ',
  },

  /* ───────────────────────────── PLANETA X ───────────────────────────── */
  planeta: {
    titulo: 'Planeta X: la misión imposible',
    etiqueta: 'PLANETA X',
    icono: '🚀',
    color: '#9b7bff',
    resumen: 'Tu nave aterrizó en un planeta desconocido. Tu equipo depende de tus decisiones para sobrevivir y volver a casa.',
    medidor: { nombre: 'Energía', de: 12, a: 100, formato: v => `${v}%` },
    intro: [
      'Año 2187. Nave exploradora <strong>KEPLER</strong>. Destino: una estación en la órbita de Marte.',
      'Nunca llegaron. Una tormenta magnética los desvió y la nave se estrelló en un planeta que no aparece en ningún mapa.',
      'El capitán está herido. La energía de la nave está al 12%. El cielo es violeta y hay dos soles.',
      'Te despiertas entre los restos y escuchas por el intercomunicador:',
      '<strong>"Tú eres el/la siguiente al mando. Necesitamos que decidas."</strong>',
    ],
    escenas: [
      {
        q: 'Q00',
        texto: ['Tu traje espacial hace un diagnóstico automático. Además del oxígeno y la temperatura, mide algo que nunca habías notado:',
          '<em>"NIVEL DE ENERGÍA INTERIOR DEL TRIPULANTE."</em>'],
        pregunta: 'Si fueras honesto(a) con el escáner, ¿cómo está tu batería estas semanas?',
        opciones: {
          llena: '🔋 Llena: me siento bien',
          media: '🔋 A la mitad: bien, pero cansado(a)',
          baja: '🪫 Baja: me está costando',
          critica: '🪫 Casi vacía: estoy agotado(a) por dentro',
          apagada: '⚫ Apagada: siento que ya no puedo más',
        },
      },
      {
        q: 'Q02',
        texto: ['Los sobrevivientes se reúnen junto a los restos del motor. Son 9. Algunos ya formaron grupitos y hablan en voz baja.',
          'Tú eres de los más nuevos en la tripulación.'],
        pregunta: '¿Qué haces?',
        opciones: {
          integra: 'Me acerco y me uno a la conversación',
          espera: 'Espero a que alguien me llame',
          margen: 'Me quedo aparte revisando mi equipo',
          ausente: 'Estoy ahí, pero quisiera estar en la Tierra',
        },
      },
      {
        q: 'Q01',
        texto: ['El sistema de navegación murió. Hay dos rutas hacia una antigua base: una segura pero de tres días; otra directa, pero nadie sabe qué hay allí.',
          'Una tormenta de arena se acerca. El equipo te mira: <strong>"¿Qué hacemos?"</strong>'],
        pregunta: 'Bajo presión, ¿qué haces?',
        opciones: {
          control: 'Decido rápido y guío al equipo',
          ayuda: 'Busco al piloto o a quien sepa más que yo',
          calma: 'Primero calmo al equipo y luego vemos',
          bloqueo: 'Me bloqueo; no puedo decidir',
          huir: 'Quiero que otro decida; no quiero esa responsabilidad',
        },
      },
      {
        q: 'Q03',
        texto: ['Primera noche en el planeta. Los dos soles se ponen. Estás en tu cápsula de descanso, mirando hacia donde debería estar la Tierra.',
          'Allá dejaste tu vida. Y tus preocupaciones.'],
        pregunta: 'De tu vida en la Tierra, ¿qué ocupa más espacio en tu cabeza últimamente? (elige hasta 3)',
      },
      {
        q: 'Q04',
        texto: ['El psicólogo de la misión te dejó un mensaje grabado: "En el espacio, lo que haces con tus emociones puede salvarte o hundirte. Conoce tus hábitos."'],
        pregunta: 'En tu vida real, ¿qué haces normalmente cuando estás mal? (elige hasta 3)',
      },
      {
        q: 'Q05',
        texto: ['Descubres que la ingeniera Vega escondió raciones de comida para ella sola. Ella era tu compañera de entrenamiento, tu amiga desde la academia.'],
        pregunta: 'Alguien en quien confiabas te falló. ¿Qué haces?',
        opciones: {
          confronta: 'Hablo con ella directamente',
          aleja: 'Me alejo; ya no cuento con ella',
          perdona: 'Me duele, pero la perdono; tenía miedo',
          desconfia: 'Desde hoy no confío en nadie del equipo',
          culpa: 'Pienso que fue mi culpa no darme cuenta',
          finge: 'Hago como si nada',
        },
      },
      {
        q: 'Q06',
        texto: ['Criaturas desconocidas rodean el campamento. La energía de los escudos está al mínimo.',
          'El capitán, herido, te toma del brazo: "Dios también está en este planeta. No tengas miedo."',
          'Pero tú sí tienes miedo.'],
        pregunta: '¿Qué pensamiento se parecería más al tuyo?',
      },
      {
        q: 'Q07',
        texto: ['Las criaturas se van. Sales a mirar el cielo: miles de estrellas que nadie había visto nunca.',
          'Te sientes diminuto(a). Y piensas en Dios.'],
        pregunta: 'Si eres completamente honesto(a), ¿cómo describirías tu relación con Dios hoy?',
      },
      {
        q: 'Q08',
        texto: ['La nave tiene una antena de largo alcance que puede enviar un mensaje más allá de cualquier galaxia conocida.',
          'Solo un mensaje. Nadie en la tripulación lo leerá.'],
        pregunta: 'Si pudieras hacerle una pregunta a Dios sin miedo a que nadie te juzgue, ¿qué le preguntarías?',
        placeholder: 'Escribe tu pregunta...',
      },
      {
        q: 'Q09',
        texto: ['La Tierra responde: "KEPLER, necesitamos un reporte honesto de su estado para mandar ayuda."',
          'El equipo quiere responder "Todo bajo control". Nadie quiere admitir que están mal.'],
        pregunta: 'En tu vida, ¿qué frases te costaría más decir cuando estás pasando por algo? (elige hasta 3)',
      },
      {
        q: 'Q10',
        texto: ['Los cascos tienen un visor que puedes programar para mostrar una frase a los demás. Toda la tripulación lo hace.',
          'Así nadie ve lo que realmente pasa detrás del vidrio.'],
        pregunta: '¿Qué frase mostraría tu visor cuando estás con otras personas?',
        opciones: { ninguna: 'Ninguna: dejo el visor transparente, soy igual en todos lados' },
      },
      {
        q: 'Q11',
        texto: ['Llegan a la base abandonada. La puerta tiene una inteligencia artificial antigua que dice:',
          '<strong>"Acceso solo para quien diga una verdad que casi nunca dice."</strong>'],
        pregunta: 'Completa: "Hay algo que últimamente me preocupa y casi nunca digo..."',
        placeholder: 'Hay algo que me preocupa y casi nunca digo...',
        boton: 'ABRIR BASE 🔓',
      },
      {
        q: 'Q12',
        texto: ['Intentas reparar el reactor... y lo sobrecargas. Una chispa, humo, y perdiste las piezas de repuesto. Fue tu error.'],
        pregunta: 'Cuando fallas en algo importante, ¿qué pasa normalmente dentro de ti?',
        opciones: {
          levanta: 'Me levanto y busco otra forma',
          insuficiente: 'Pienso que no soy suficiente para liderar',
          compara: 'Pienso que otro lo habría hecho mejor',
          culpa: 'Me culpo durante mucho tiempo',
          aprobacion: 'Necesito que alguien me diga que está bien',
          meda: 'Me desconecto; me da igual',
        },
      },
      {
        q: 'Q13',
        nivelSecreto: true,
        texto: ['En lo más profundo de la base encuentras una sala sellada. Nadie más de la tripulación sabe que existe.',
          'Esta pregunta no tiene puntos. Nadie sabrá que la respondiste tú.'],
        pregunta: '¿Hay alguna lucha personal de la que te gustaría poder hablar con alguien de confianza?',
        seguimiento: 'Si quieres, escríbela aquí. No pongas tu nombre.',
      },
      {
        q: 'Q14',
        texto: ['La nave está casi lista, pero hay un último obstáculo: un campo de asteroides. Cada asteroide lleva el nombre de algo que pesa en tu vida.',
          'Los láseres solo tienen energía para destruir uno.'],
        pregunta: 'EL JEFE FINAL: en tu vida real, ¿cuál enfrentarías primero?',
      },
      {
        q: 'Q15',
        texto: ['Antes del despegue, el capitán reúne a todos: "Nadie vuelve a casa solo. Díganme qué necesitan para llegar."'],
        pregunta: 'Pensando en tu vida real, ¿qué necesitarías de la iglesia? (elige hasta 3)',
      },
      {
        q: 'Q16',
        texto: ['Despegan. El planeta violeta se hace pequeño. Y en la pantalla aparece la Tierra: azul, lejana, pero ahí está.',
          'Descubriste que tu valor no dependía de no fallar. Tu equipo te siguió porque nunca los abandonaste.'],
        pregunta: 'Camino a casa: si pudieras pedirle una sola cosa a Dios para esta etapa de tu vida, ¿qué sería?',
        placeholder: 'Le pediría...',
      },
    ],
    cierre: 'MISIÓN CUMPLIDA',
  },

  /* ───────────────────────────── EL REINO ───────────────────────────── */
  reino: {
    titulo: 'El Reino Perdido',
    etiqueta: 'EL REINO',
    icono: '👑',
    color: '#4fbf7a',
    resumen: 'Un reino dividido. Traiciones, miedo y decisiones difíciles. Para recuperar la corona tendrás que descubrir en quién confiar.',
    medidor: { nombre: 'Fragmentos de corona', de: 0, a: 17, formato: v => `${v}/17` },
    intro: [
      'El reino de <strong>Aurelia</strong> vivía en paz... hasta la noche en que la corona fue robada y rota en pedazos.',
      'Sin corona, los nobles pelean entre ellos, el pueblo tiene miedo y las sombras empiezan a cubrir los caminos.',
      'Tú eres un(a) joven escudero(a) del castillo. Nadie esperaba nada de ti.',
      'Pero el anciano consejero te entrega un mapa y te dice:',
      '<strong>"Los fragmentos de la corona solo aparecen ante alguien que dice la verdad. Por eso te elegí a ti."</strong>',
    ],
    escenas: [
      {
        q: 'Q00',
        texto: ['Antes de partir, el consejero te lleva ante una fuente de agua cristalina. "Esta agua refleja cómo está tu alma, no tu cara", dice.',
          'Te inclinas a mirar.'],
        pregunta: '¿Qué ves? ¿Cómo está tu energía estas últimas semanas?',
        opciones: {
          llena: '🔋 Llena: me siento bien',
          media: '🔋 A la mitad: bien, pero cansado(a)',
          baja: '🪫 Baja: me está costando',
          critica: '🪫 Casi vacía: estoy agotado(a) por dentro',
          apagada: '⚫ Apagada: siento que ya no puedo más',
        },
      },
      {
        q: 'Q02',
        texto: ['Llegas a la taberna del pueblo, donde se reúnen los que se unirán a la búsqueda. Ríen, brindan, se cuentan historias.',
          'Nadie te conoce.'],
        pregunta: '¿Qué haces?',
        opciones: {
          integra: 'Me siento con ellos y empiezo a platicar',
          espera: 'Espero a que alguien me invite a la mesa',
          margen: 'Me siento solo(a) en una esquina a observar',
          ausente: 'Estoy ahí, pero quisiera estar en otro lugar',
        },
      },
      {
        q: 'Q01',
        texto: ['Un ejército de sombras ataca la taberna. Las mesas vuelan, la gente grita, el fuego se extiende.',
          'Alguien grita tu nombre: <strong>"¡Escudero(a)! ¿Qué hacemos?"</strong>'],
        pregunta: '¿Qué haces?',
        opciones: {
          control: 'Tomo una espada y organizo la defensa',
          ayuda: 'Busco al capitán de la guardia',
          calma: 'Protejo y calmo a los niños y ancianos',
          bloqueo: 'Me quedo paralizado(a)',
          huir: 'Busco la salida más cercana',
        },
      },
      {
        q: 'Q03',
        texto: ['Esa noche acampan en el bosque. Los demás duermen junto al fuego. Tú no puedes.',
          'Las sombras no son lo único que te persigue. También te siguen tus pensamientos.'],
        pregunta: '¿Qué ocupa más espacio en tu cabeza últimamente? (elige hasta 3)',
      },
      {
        q: 'Q04',
        texto: ['Una anciana del grupo, que tampoco duerme, se sienta a tu lado. "Todos tenemos nuestra forma de sobrevivir a las noches largas", te dice. "¿Cuál es la tuya?"'],
        pregunta: 'En tu vida real, ¿qué haces normalmente cuando estás mal? (elige hasta 3)',
      },
      {
        q: 'Q05',
        texto: ['Descubres que Aldric, el caballero que te entrenó desde niño(a), fue quien robó la corona. Te usó para acercarse al rey.'],
        pregunta: 'La persona en la que más confiabas te traicionó. ¿Qué haces?',
        opciones: {
          confronta: 'Lo busco y lo confronto',
          aleja: 'Me alejo; ya no quiero saber de él',
          perdona: 'Me duele, pero decido perdonarlo',
          desconfia: 'No vuelvo a confiar en nadie de este reino',
          culpa: 'Pienso que fue mi culpa por confiar',
          finge: 'Hago como si nada hubiera pasado',
        },
      },
      {
        q: 'Q06',
        texto: ['Cruzan el Valle de la Niebla. Las sombras rodean al grupo; no se ve nada.',
          'El monje del grupo empieza a cantar: "El Rey verdadero nos cuida. No tenemos nada que temer."',
          'Pero tu espada tiembla en tu mano.'],
        pregunta: '¿Qué pensamiento se parecería más al tuyo?',
      },
      {
        q: 'Q07',
        texto: ['Llegan a una capilla en ruinas en lo alto de la montaña. Todos entran a descansar.',
          'Tú te arrodillas al fondo, donde nadie te ve.'],
        pregunta: 'Si eres completamente honesto(a), ¿cómo describirías tu relación con Dios hoy?',
      },
      {
        q: 'Q08',
        texto: ['En la capilla hay un muro lleno de pergaminos: preguntas que los peregrinos le han dejado a Dios durante siglos.',
          'Tomas un pergamino en blanco. Nadie sabrá cuál es el tuyo.'],
        pregunta: 'Si pudieras hacerle una pregunta a Dios sin miedo a que nadie te juzgue, ¿qué le preguntarías?',
        placeholder: 'Escribe tu pregunta...',
      },
      {
        q: 'Q09',
        texto: ['Para cruzar el puente del guardián, cada viajero debe decir en voz alta una frase que le cueste decir.',
          'Muchos se han dado la vuelta ahí mismo.'],
        pregunta: '¿Qué frases te costaría más decirle a alguien cuando estás pasando por algo? (elige hasta 3)',
      },
      {
        q: 'Q10',
        texto: ['Para entrar al castillo del traidor deben disfrazarse en un baile de la corte. Cada máscara tiene una frase bordada.',
          'Te das cuenta de que ya conoces esas frases. Las has usado antes.'],
        pregunta: '¿Cuál se parece más a la que tú usas cuando estás con otras personas?',
        opciones: { ninguna: 'Ninguna: entro sin máscara, soy igual en todos lados' },
      },
      {
        q: 'Q11',
        texto: ['Encuentras el cofre donde Aldric guarda el fragmento más grande. En la tapa está grabado:',
          '<strong>"Solo lo abre quien confiesa una verdad que casi nunca dice."</strong>'],
        pregunta: 'Completa: "Hay algo que últimamente me preocupa y casi nunca digo..."',
        placeholder: 'Hay algo que me preocupa y casi nunca digo...',
        boton: 'ABRIR COFRE 🔓',
      },
      {
        q: 'Q12',
        texto: ['Los guardias te descubren. Por tu error, capturan a dos de tus compañeros.'],
        pregunta: 'Cuando fallas y otros pagan el precio, ¿qué pasa normalmente dentro de ti?',
        opciones: {
          levanta: 'Me levanto y busco cómo arreglarlo',
          insuficiente: 'Pienso que no soy digno(a) de esta misión',
          compara: 'Pienso que un verdadero caballero no habría fallado',
          culpa: 'Me culpo durante mucho tiempo',
          aprobacion: 'Necesito que alguien me diga que está bien',
          meda: 'Me desconecto; me da igual',
        },
      },
      {
        q: 'Q13',
        nivelSecreto: true,
        texto: ['Tras un tapiz encuentras un pasadizo secreto que solo conocían los reyes antiguos.',
          'Aquí no hay puntos ni recompensas. Nadie sabrá que la respondiste tú.'],
        pregunta: '¿Hay alguna lucha personal de la que te gustaría poder hablar con alguien de confianza?',
        seguimiento: 'Si quieres, escríbela aquí. No pongas tu nombre.',
      },
      {
        q: 'Q14',
        texto: ['En el salón del trono te esperan los guardianes del traidor. No son soldados: son las cosas que han estado dividiendo el reino... y tu corazón.',
          'Solo puedes enfrentar a uno.'],
        pregunta: 'EL JEFE FINAL: en tu vida real, ¿cuál enfrentarías primero?',
      },
      {
        q: 'Q15',
        texto: ['Tus compañeros liberados llegan a tu lado. El monje te pone una mano en el hombro: "Nadie gana esta batalla solo. ¿Qué necesitas de nosotros?"'],
        pregunta: 'Pensando en tu vida real, ¿qué necesitarías de la iglesia? (elige hasta 3)',
      },
      {
        q: 'Q16',
        texto: ['Unes el último fragmento. La corona brilla... y entiendes el secreto: nunca fue para ti.',
          'El trono de Aurelia siempre tuvo un Rey. Un Rey que no vino a ser servido, sino a servir, y que cargó sobre sí lo que su pueblo no podía cargar.',
          'Tu misión no era gobernar. Era volver a casa.'],
        pregunta: 'Si pudieras pedirle una sola cosa a Dios para esta etapa de tu vida, ¿qué sería?',
        placeholder: 'Le pediría...',
      },
    ],
    cierre: 'EL REINO HA SIDO RESTAURADO',
  },
};
